version: 2

jobs:
  Apollo Client:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run: cd client && npm ci
      - run: cd client && npx apollo client:check || echo 'validation failed'

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd client && npx apollo client:push
          fi

  Apollo Server:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run: cd server && npm i

      - run:
          name: Output schema locally
          command: cd server && node scripts/publish.js

      - run: cd server && npx apollo service:check --validationPeriod=P3D || echo 'validation failed'

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd server && npx apollo service:push
          fi

workflows:
  version: 2
  Build and Test:
    jobs:
      - Apollo Client
      - Apollo Server
