version: 2

jobs:
  Apollo Client:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
          name: Attempt to restore node_modules cache (keyed on package-lock.json and circle config)
          keys:
            - client-node-modules-cache--{{ checksum "client/package-lock.json" }}--{{ checksum ".circleci/config.yml" }}
      - run: cd client && npm ci
      - save_cache:
          name: Save node_modules cache (keyed on package-lock.json and circle config)
          key: client-node-modules-cache--{{ checksum "client/package-lock.json" }}--{{ checksum ".circleci/config.yml" }}
          paths:
            - client/node_modules
      - run: cd client && npx apollo client:check || echo 'validation failed'

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd client && npx apollo client:push
          fi

  Apollo Server:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
          name: Attempt to restore node_modules cache (keyed on package-lock.json and circle config)
          keys:
            - server-node-modules-cache--{{ checksum "server/package-lock.json" }}--{{ checksum ".circleci/config.yml" }}
      - run: cd server && npm i
      - save_cache:
          name: Save node_modules cache (keyed on package-lock.json and circle config)
          key: server-node-modules-cache--{{ checksum "server/package-lock.json" }}--{{ checksum ".circleci/config.yml" }}
          paths:
            - server/node_modules
      - run:
          name: Output schema locally
          command: cd server && node scripts/publish.js

      - run: cd server && npx apollo service:check --validationPeriod=P3D || echo 'validation failed'

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd server && npx apollo service:push
          fi

workflows:
  version: 2
  Build and Test:
    jobs:
      - Apollo Client
      - Apollo Server
